# CodeRabbit 設定ファイル
# https://docs.coderabbit.ai/getting-started/configure-coderabbit

language: ja-JP

reviews:
  # PRのドラフトもレビュー対象にする
  request_changes_workflow: false
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: false

  # 自動レビューの設定
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
      - develop

  # レビューから除外するパスを設定
  path_filters:
    - "!**/node_modules/**"
    - "!**/.next/**"
    - "!**/dist/**"
    - "!**/*.lock"
    - "!**/package-lock.json"

  # レビューの重点項目
  finishing_touches:
    docstrings:
      enabled: false

chat:
  auto_reply: true

knowledge_base:
  # プロジェクト固有の情報をCodeRabbitに伝える
  learnings:
    scope: auto

  # ドキュメントをナレッジベースとして登録
  opt_out: false
