version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
  settings:
    govet:
      enable-all: true
    errcheck:
      check-type-assertions: true
      check-blank: true

formatters:
  enable:
    - gofmt

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
