// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Repository struct {
	ID          uuid.UUID             `json:"id"`
	Owner       string                `json:"owner"`
	Name        string                `json:"name"`
	FullName    string                `json:"full_name"`
	SummaryJson pqtype.NullRawMessage `json:"summary_json"`
	CreatedAt   time.Time             `json:"created_at"`
	UpdatedAt   time.Time             `json:"updated_at"`
}

type RepositoryFile struct {
	ID           uuid.UUID `json:"id"`
	RepositoryID uuid.UUID `json:"repository_id"`
	FilePath     string    `json:"file_path"`
	Content      string    `json:"content"`
	CreatedAt    time.Time `json:"created_at"`
}

type Room struct {
	ID        uuid.UUID `json:"id"`
	Player1ID uuid.UUID `json:"player1_id"`
	Player2ID uuid.UUID `json:"player2_id"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID             uuid.UUID `json:"id"`
	GithubID       int64     `json:"github_id"`
	GithubLogin    string    `json:"github_login"`
	GnuBalance     int32     `json:"gnu_balance"`
	Rate           int32     `json:"rate"`
	EncryptedToken string    `json:"encrypted_token"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}
