// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID             uuid.UUID `json:"id"`
	GithubID       int64     `json:"github_id"`
	GithubLogin    string    `json:"github_login"`
	GnuBalance     int32     `json:"gnu_balance"`
	Rate           int32     `json:"rate"`
	EncryptedToken string    `json:"encrypted_token"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}
