// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUserByGitHubID(ctx context.Context, githubID int64) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	UpdateGnuBalance(ctx context.Context, arg UpdateGnuBalanceParams) error
}

var _ Querier = (*Queries)(nil)
