// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetRoomByID(ctx context.Context, id uuid.UUID) (Room, error)
	GetUserByGitHubID(ctx context.Context, githubID int64) (User, error)
	GetUserByGitHubLogin(ctx context.Context, githubLogin string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	UpdateGnuBalance(ctx context.Context, arg UpdateGnuBalanceParams) error
	UpdateRoomStatus(ctx context.Context, arg UpdateRoomStatusParams) error
}

var _ Querier = (*Queries)(nil)
