// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (github_id, github_login, encrypted_token)
VALUES ($1, $2, $3)
RETURNING id, github_id, github_login, gnu_balance, rate, encrypted_token, created_at, updated_at
`

type CreateUserParams struct {
	GithubID       int64  `json:"github_id"`
	GithubLogin    string `json:"github_login"`
	EncryptedToken string `json:"encrypted_token"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.GithubID, arg.GithubLogin, arg.EncryptedToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.GithubLogin,
		&i.GnuBalance,
		&i.Rate,
		&i.EncryptedToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGitHubID = `-- name: GetUserByGitHubID :one
SELECT id, github_id, github_login, gnu_balance, rate, encrypted_token, created_at, updated_at FROM users WHERE github_id = $1
`

func (q *Queries) GetUserByGitHubID(ctx context.Context, githubID int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByGitHubID, githubID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.GithubLogin,
		&i.GnuBalance,
		&i.Rate,
		&i.EncryptedToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGitHubLogin = `-- name: GetUserByGitHubLogin :one
SELECT id, github_id, github_login, gnu_balance, rate, encrypted_token, created_at, updated_at FROM users WHERE github_login = $1
`

func (q *Queries) GetUserByGitHubLogin(ctx context.Context, githubLogin string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByGitHubLogin, githubLogin)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.GithubLogin,
		&i.GnuBalance,
		&i.Rate,
		&i.EncryptedToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, github_id, github_login, gnu_balance, rate, encrypted_token, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.GithubLogin,
		&i.GnuBalance,
		&i.Rate,
		&i.EncryptedToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGnuBalance = `-- name: UpdateGnuBalance :exec
UPDATE users SET gnu_balance = GREATEST(0, $2), updated_at = NOW() WHERE id = $1
`

type UpdateGnuBalanceParams struct {
	ID         uuid.UUID `json:"id"`
	GnuBalance int32     `json:"gnu_balance"`
}

func (q *Queries) UpdateGnuBalance(ctx context.Context, arg UpdateGnuBalanceParams) error {
	_, err := q.db.ExecContext(ctx, updateGnuBalance, arg.ID, arg.GnuBalance)
	return err
}
